//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BId { get; set; }
        [Required]
        public string bname { get; set; }
        [Required]
        public string author { get; set; }
        [Required]
        public string edition { get; set; }
        [Required]
        public Nullable<int> CId { get; set; }
        [Required]
        public string price { get; set; }
        [Required]
        public string stock { get; set; }
       
        public string discount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
